//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StPeters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StPeters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head/&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Glorious Mysteries&lt;/h2&gt;
        ///    &lt;h3&gt;1. The Resurrection &lt;/h3&gt;    
        ///    &lt;p&gt;Mary Magdalene and the other Mary came to see the tomb. An angel appeared and said, &quot;Do not be afraid! I know that you are seeking Jesus the crucified. He is not here, for He has been raised just as He said.&quot; (Mt 28:1-10) &lt;/p&gt;    
        ///    &lt;h3&gt;2. The Ascension of Our Lord &lt;/h3&gt;    
        ///    &lt;p&gt;As Jesus blessed them He parted from them and was taken up to heaven. (Lk 24:44-53) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string glorious {
            get {
                return ResourceManager.GetString("glorious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head/&gt;
        ///&lt;body&gt;
        ///&lt;h2&gt;Joyful Mysteries&lt;/h2&gt;
        ///&lt;h3&gt;1. The Annunciation &lt;/h3&gt;    
        ///&lt;p&gt;The angel Gabriel was sent from God to a town of Galilee called Nazareth. And coming to Mary, he said, &quot;Hail, favored one! The Lord is with you.&quot; (Lk 1:26-28) &lt;/p&gt;   
        ///&lt;h3&gt;2. The Visitation &lt;/h3&gt;    
        ///&lt;p&gt;Mary set out and traveled to the house of Zechariah and greeted Elizabeth. When Elizabeth heard Mary’s greeting, the infant leaped in her womb, and Elizabeth, filled with the Holy  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string joyful {
            get {
                return ResourceManager.GetString("joyful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head/&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Luminous&lt;/h2&gt;
        ///    &lt;h3&gt;1. The Baptism in the Jordan &lt;/h3&gt;    
        ///    &lt;p&gt;And a voice came from the heavens, saying, &quot;This is my beloved Son, with whom I am well pleased.&quot; (Mt. 3:17) &lt;/p&gt;
        ///    &lt;h3&gt;2. The Wedding at Cana &lt;/h3&gt;
        ///    &lt;p&gt;&quot;Women, how does your concern affect me? My hour has not yet come.&quot; His mother said to the servers, &quot;Do whatever he tells you.&quot; (Jn 2:1-12) &lt;/p&gt;    &lt;p&gt; &lt;/p&gt;    
        ///    &lt;h3&gt;3. The Proclamation of the Kingdom of God [rest of string was truncated]&quot;;.
        /// </summary>
        public static string luminous {
            get {
                return ResourceManager.GetString("luminous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;h2&gt;Prayers of the Rosary&lt;/h2&gt;      
        ///    &lt;p&gt;&lt;b&gt;Apostles’ Creed:&lt;/b&gt; I believe in God, the Father almighty, Creator of heaven and earth, and in Jesus Christ, His only Son, our Lord, who was conceived by the Holy Spirit, born of the Virgin Mary, suffered under Pontius Pilate, was crucified, died and was buried.  He descended into hell.  On the third day He rose again from the dead; he ascended into heaven, and is [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prayers {
            get {
                return ResourceManager.GetString("prayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head/&gt;
        ///&lt;body&gt;
        ///    &lt;h2&gt;Sorrowful Mysteries&lt;/h2&gt;
        ///    &lt;h3&gt;1. The Agony in the Garden &lt;/h3&gt;    
        ///    &lt;p&gt;Jesus went to a place called Gethsemane to pray. &quot;My Father, if it is possible, let this cup pass from me; yet, not as I will, but as you will.&quot; (Mt 26:36-46) &lt;/p&gt;    
        ///    &lt;h3&gt;2. The Scourging at the Pillar &lt;/h3&gt;    
        ///    &lt;p&gt;The chief priests with the elders and the scribes held a council. They bound Jesus, led him away, and handed him over to Pilate. Pilate, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string sorrowful {
            get {
                return ResourceManager.GetString("sorrowful", resourceCulture);
            }
        }
    }
}
